#ifndef UNISANGULARDISTRIBUTION_H
#define UNISANGULARDISTRIBUTION_H

#include <map>
#include <TH1D.h>

class UNISAngularDistribution
{
public :
  TH1D * fAngularDistribution;
  std::map<int, UNISAngularDistribution *> fSecondaryDecayAngularDistribution; //Angular distribution of secundary particles generated by its decay
};


#endif
